---
- name: 1. Setting up repository
  copy:
    src: cri-o.repo
    dest: /etc/yum.repos.d/cri-o.repo

- name: 2. Install the required package
  dnf:
    name: "{{ crio_pkg }}"
    state: present
  ignore_errors: true

- name: 3. Start the relevant service
  service:
    name: "{{ crio_svc }}"
    state: started
    enabled: true
  ignore_errors: true
