---
- name: 1. Kubernetes initialization on master
  ansible.builtin.shell: "kubeadm init --apiserver-advertise-address={{ API_SERVER_IP }} --pod-network-cidr={{ INTERNAL_POD_NETWORK }}"
  register: kubeadmin_init
  when: not kubernetes_init_stat.stat.exists
  become: true

- name: 2. Creating requird directory structure
  ansible.builtin.shell: "{{ item }}"
  loop: "{{ POST_INITIALIZATION_COMMANDS }}"
  when: not kubernetes_init_stat.stat.exists
  become: false


- name: 3. Generate join command
  ansible.builtin.command: "{{ CLUSTER_JOIN_COMMAND }}"
  register: joinWorkerNodes
  become: true

- name: 13.4. Setting up the command use globally
  set_fact: 
     kubernetes_join_workers: "{{ joinWorkerNodes.stdout }}"
  when: joinWorkerNodes.stdout is defined
  become: true
