---
- name: 1. Add a new DNF repository 
  ansible.builtin.yum_repository: 
    name: kubernetes
    description: "Kubernetes Package Repository" 
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/ 
    gpgcheck: yes 
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key 
    enabled: yes
    exclude: "kubelet,kubeadm,kubectl,cri-tools,kubernetes-cni"

- name: 2. Install the required package
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  loop: "{{ KUBERNETES_PACKAGES }}"
  ignore_errors: true

- name: 3. Start the relevant service
  ansible.builtin.service:
    name: "{{ KUBELET_SERVICE }}"
    state: started
    enabled: true
  ignore_errors: true

